#coding=utf-8
import urllib2,json,tools
'''
<?xml version="1.0" encoding="UTF-8"?>

<tv generator-info-name="Generated by EPGGUIDE. Visit http://epgguide.net for more information." generator-info-url="http://epgguide.net">

    <channel id="cctv1.cn">
        <display-name lang="zh">CCTV 1 CN</display-name>
    </channel>
    <programme start="20180222044300 +0000" stop="20180222071500 +0000" channel="cctv1.cn">
        <title lang="zh">星光大道2018-9 星光大道嘉年华（130分钟）</title>
    </programme>

</tv>
'''
'''
{ 'tv':{
        {'channel':{
                'dispaly-name':

            }
        }
}
}

'''

####API网址

Interface="http://api.cntv.cn/epg/epginfo"




################base#####################

#向interface提交参数过去节目列表 json格式
def createJsonWithTVname(name,date):

    file=urllib2.urlopen(Interface+"?"+"c="+name+"&serviceId=channel&d="+tools.timetofomat(date)+"&t=json")
    ###json 格式
    parser = json.load(file,encoding="utf-8")

    return parser[name]

###从tv节目列表中获取节目列表--->list
def getProgramsWithTV(tvParser):

    islive=""

    programs=tvParser['program']

    return islive,programs


###从节目列表获取节目开始结束时间---->str ,start,stop
def getDateWithElement(ele,d):
    start=ele['showTime']
    duration=ele["duration"]

    return tools.startime(start,d),tools.stoptime(start,duration,d)
def getNameOfprograms(ele):
    name=ele['t'].encode("utf-8")
    return name
